### ISSUE TITLE
Source directories must not be nested

### ISSUE THREAD

**Issue by kane77** [scoverage/sbt-coveralls#73]
Hi,
I'm trying a very simple build with coveralls, but it fails with this error:
ava.lang.IllegalArgumentException: requirement failed: Source directories must not be nested

It's a single module buils and contains one src/main/scala directory

build.sbt only contains:

lazy val sprayVersion = "1.3.2"
organization := "com.example"
version := "0.1.0"
scalaVersion := "2.11.5"
name := "coveralls-test"
libraryDependencies ++= Seq(
  "commons-codec" % "commons-codec" % "1.10",
  "io.spray" %% "spray-json" % sprayVersion,
  "io.spray" %% "spray-client" % sprayVersion,
  "com.typesafe.scala-logging" %% "scala-logging" % "3.1.0",
  "ch.qos.logback" % "logback-classic" % "1.1.3",
  "ch.qos.logback" % "logback-core" % "1.1.3",
  "com.typesafe.akka" %% "akka-actor" % "2.3.14",
  "org.scalatest" %% "scalatest" % "2.2.4" % Test,
  "junit" % "junit" % "4.12" % Test,
  "org.pegdown" % "pegdown" % "1.1.0" % Test)

Any ideas?

**Comment by earldouglas** [comment]
I just ran into this as well.  It looks `isChild` will detect any given directory as a child of itself:

https://github.com/scoverage/sbt-coveralls/blob/bc98aa3baf6892c063a884e30e31cfc6141905e5/src/main/scala/org/scoverage/coveralls/CoberturaMultiSourceReader.scala#L28

**Comment by reid-spencer** [comment]
This is biting me too. Looks like I'm headed for a downgrade of sbt-scoverage and sbt-coveralls plugins as well. :-1:

**Comment by AndrewWhitaker** [comment]
What's odd is that there's a [test case](https://github.com/scoverage/sbt-coveralls/blob/bc98aa3baf6892c063a884e30e31cfc6141905e5/src/test/scala/com/github/theon/coveralls/CoberturaMultiSourceReaderTest.scala#L45) that explicitly checks to make sure that the result of calling `isChild` with identical `child` and `parent` is `true`. Is this by design? The fix is easy enough, like @earldouglas pointed out.

**Comment by earldouglas** [comment]
> Is this by design?

It does [appear to be by design], however only [the one test case] appears to rely on it.

[appear to be by design]: https://github.com/scoverage/sbt-coveralls/blob/bc98aa3baf6892c063a884e30e31cfc6141905e5/src/main/scala/org/scoverage/coveralls/CoberturaMultiSourceReader.scala#L26
[the one test case]: https://github.com/scoverage/sbt-coveralls/blob/bc98aa3baf6892c063a884e30e31cfc6141905e5/src/test/scala/com/github/theon/coveralls/CoberturaMultiSourceReaderTest.scala#L45

This could be addressed simply by changing `isChild` to:

```scala
def isChild(child: File, parent: File): Boolean =
  sbt.IO.relativize(parent, child).isDefined
```

and changing that test case to expect `false`.

**Comment by jackewitz** [comment]
I just ran into this as well with:
- sbt-scoverage 1.3.3
- sbt-coveralls 1.0.3

Which versions should I use to get your bugfix? Have you released a stable version of sbt-coveralls (or combination of sbt-scoverage and sbt-coveralls) already?

**Comment by zzztimbo** [comment]
I'm using the same versions as @jackewitz and having the same issues.

**Comment by zzztimbo** [comment]
@jackewitz this pull request answers your questions about which versions to use:

https://github.com/alexandru/shade/pull/21/files

**Comment by zzztimbo** [comment]
Has anyone run into this issue after downgrading? https://github.com/scoverage/sbt-coveralls/issues/56

**Comment by ozoli** [comment]
@zztimbo I had no issues using the versions shown in the pull request ie.

```scala
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.0.1")
addSbtPlugin("org.scoverage" % "sbt-coveralls" % "1.0.0")
```

**Comment by jackewitz** [comment]
I had no issues using the versions shown at @ozoli comment. Great. :-)

**Comment by jeffmay** [comment]
I just encountered this with sbt-scoverage 1.3.5 and sbt-coveralls 1.0.3 as well.
My fix was to downgrade to sbt-scoverage 1.0.1 and sbt-coveralls 1.0.0 as recommended as well.

**Comment by ruippeixotog** [comment]
Despite being closed, this issue still affects many users as there's no published version of the two plugins since then. I'll have to downgrade them in my project too, but downgrading from sbt-scoverage 1.3.5 to 1.0.3 seems a big jump... @sksamuel, is there any idea of when might you release a new version?

**Comment by sksamuel** [comment]
I've put coveralls 1.1.0 onto maven central (note: not bintray)

**Comment by ruippeixotog** [comment]
@sksamuel thank you for your quick action, I was able to make it work now with sbt-scoverage 1.3.5 and sbt-coveralls 1.1.0!

However, I had to run `coverageReport` between the `test` and `coverall` tasks. Otherwise, I get a `java.io.FileNotFoundException` on `coveralls`, saying that it didn't found `coverage-report/cobertura.xml`. Is running `coverageReport` now required? If so, can you update the README so that it includes this?

Thank you once more!
