### ISSUE TITLE
use COVERALLS_SERVICE_JOB_ID to identify build

### ISSUE THREAD

**Issue by callicles** [scoverage/sbt-coveralls#94]
Right now only travis is supported. Making it a bit more generic would enable support for other cis.

Ref: https://github.com/nickmerwin/node-coveralls

**Comment by nakkurt** [comment]
Also interested in this -- currently we're unable to set up [PARALLEL BUILDS](https://docs.coveralls.io/parallel-build-webhook) because we're using CircleCi and it seems _sbt-coveralls_ doesn't support parallel builds when using Circleci? 

Followed instructions [here](https://github.com/lemurheavy/coveralls-public/issues/1191#issuecomment-425493026) (substituted CIRCLE_BUILD_ID with the correct env var CIRCLE_BUILD_NUM, as the '_ID' was likely a typo) and still getting `{"error":"No build matching CI build number fb48426b-988b-430f-abe2-2a5ebbcfe327 found"}%`.

Seems like using `COVERALLS_SERVICE_JOB_ID` would help **sbt-coveralls** get closer to feature parity.  
    
(Unrelated, but possibly helpful : sbt-coveralls would also need to check whether  `COVERALLS_PARALLEL: true` env var has been set to actually support parallel builds )

**Comment by rolandtritsch** [comment]
Old. Closing. Please reopen when needed.
